In [ ]:
import numpy as np

In [ ]:
a = np.ones((4,3)).astype("int")

In [ ]:
a.shape


(4, 3)

In [ ]:
len(a.shape)

2

In [ ]:
a.shape[0]*a.shape[1]

12

In [ ]:
a = np.array([1] * 12).reshape(4,3)

In [ ]:
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
b = np.array(["rabbit","wolf"]*2*2).reshape(2,4)
b

array([['rabbit', 'wolf', 'rabbit', 'wolf'],
       ['rabbit', 'wolf', 'rabbit', 'wolf']], dtype='<U6')

In [ ]:
b[(1,3)] = "supercalifragilisticexpialidocious"
b

array([['rabbit', 'wolf', 'rabbit', 'wolf'],
       ['rabbit', 'wolf', 'rabbit', 'superc']], dtype='<U6')

In [ ]:
b = b.astype("<U40")
b

array([['rabbit', 'wolf', 'rabbit', 'wolf'],
       ['rabbit', 'wolf', 'rabbit', 'supercalifragilisticexpialidoc']],
      dtype='<U40')

In [ ]:
b[(1,3)] = "supercalifragilisticexpialidocious"
b

array([['rabbit', 'wolf', 'rabbit', 'wolf'],
       ['rabbit', 'wolf', 'rabbit', 'supercalifragilisticexpialidocious']],
      dtype='<U40')

In [ ]:
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
a[:,2]

array([1, 1, 1, 1])

In [ ]:
a[:,2] = 10
a

array([[ 1,  1, 10],
       [ 1,  1, 10],
       [ 1,  1, 10],
       [ 1,  1, 10]])

In [ ]:
a[:,-1] = 15
a

array([[ 1,  1, 15],
       [ 1,  1, 15],
       [ 1,  1, 15],
       [ 1,  1, 15]])

In [ ]:
a[1,:2] = 2
a

array([[ 1,  1, 15],
       [ 2,  2, 15],
       [ 1,  1, 15],
       [ 1,  1, 15]])

In [ ]:
a[-1,-1] = a[-1,-1]*a[-1,-1]
a

array([[    1,     1,    15],
       [    2,     2,    15],
       [    1,     1,    15],
       [    1,     1, 50625]])