In [1]:
import numpy as np

In [2]:
a = np.array(["a","b","c"])
a

array(['a', 'b', 'c'], dtype='<U1')

In [3]:
a[[2,0]]

array(['c', 'a'], dtype='<U1')

In [7]:
b = np.array([[3,2,1],[7,6,5]])
b

array([[3, 2, 1],
       [7, 6, 5]])

In [10]:
b[[1]]

array([[7, 6, 5]])

In [11]:
b[:,1]

array([2, 6])

In [12]:
b.shape

(2, 3)

In [15]:
for x in b.flat : print(x)

3
2
1
7
6
5


In [16]:
b.flat[b.argmax()]

7

In [17]:
b.flat[b.argmin()]

1

In [18]:
f = lambda x,y :x*y

In [19]:
f(4,3)

12